# Generated by Django 6.0.5 on 2026-05-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Procurement/Fuel'), ('utility', 'Utility Consumption'), ('travel', 'Corporate Travel')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_record_count', models.IntegerField(default=0)),
                ('emission_record_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_json', models.JSONField()),
                ('ingestion_status', models.CharField(choices=[('raw', 'Raw/Unparsed'), ('parsed', 'Successfully parsed'), ('error', 'Parsing failed')], default='raw', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='api.datasource')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('activity_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('activity_unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('emission_factor_used', models.DecimalField(decimal_places=6, max_digits=10)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('error', 'Error')], default='valid', max_length=20)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_record', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='api.rawrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
