# Generated by Django 6.0.5 on 2026-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rawrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='file_size_bytes',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='ingestion_status',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='rawrecord',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='rawrecord',
            name='ingestion_status',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20),
        ),
        migrations.DeleteModel(
            name='EmissionRecord',
        ),
    ]
