# Generated by Django 6.0.5 on 2026-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_datasource_options_alter_rawrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('activity_value', models.FloatField()),
                ('activity_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.FloatField()),
                ('validation_status', models.CharField(default='valid', max_length=20)),
                ('approval_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
