# Generated by Django 6.0.5 on 2026-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emissionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='validation_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
